### ISSUE TITLE
ij-shared-indexes-tool-cli execute failed on windows11

### ISSUE THREAD

**Issue by intellijboy** [JetBrains/intellij-shared-indexes-tool-example#1]
STDIN is empty: true
2023-06-30 00:32:02.452 [main] INFO  c.i.extras.common.process.ExecUtil -   ... started external process for IJ
2023-06-30 00:32:02.488 [main] INFO  c.i.extras.common.process.ExecUtil -   ... failed external process for IJ with exit code 1
2023-06-30 00:32:02.490 [main] INFO  c.i.extras.runner.IntelliJRunner - IU-231.9011.34 completed with code: 1
Exception in thread "main" java.lang.IllegalStateException: Non-zero exit code during shared indexes version retrieving, see logs in D:\repositories\ideaIndexes\spring-framework\temp\ij-tmp-1688056322162\log
        at com.intellij.extras.runner.IntelliJRunnerKt.checkSuccessful(IntelliJRunner.kt:24)
        at com.intellij.indexing.shared.builder.IntelliJSharedIndexesVersionBuilder.build(IntelliJSharedIndexesVersionBuilder.kt:52)
        at com.intellij.indexing.shared.builder.IntelliJSharedIndexesBuilder.build(IntelliJSharedIndexesBuilder.kt:113)
        at com.intellij.indexing.shared.builder.IntelliJSharedIndexesBuilder.buildAndUpload(IntelliJSharedIndexesBuilder.kt:176)
        at com.intellij.indexing.shared.builder.IntelliJSharedIndexesBuilder.buildAndUpload(IntelliJSharedIndexesBuilder.kt:92)
        at com.intellij.indexing.shared.builder.ShortcutsKt.buildSharedIndexesForLocalServer(Shortcuts.kt:70)
        at com.intellij.indexing.shared.builder.ShortcutsKt.buildSharedIndexesAndStartServerOnThem(Shortcuts.kt:52)
        at com.intellij.indexing.shared.builder.ShortcutsKt.buildSharedIndexesAndStartServerOnThem$default(Shortcuts.kt:42)
        at com.intellij.indexing.shared.builder.MainKt.main(Main.kt:36)

**Comment by sproshev** [comment]
Hi! There should be logs in `dataDir`, could you please attach them?

**Comment by sproshev** [comment]
Oh, sorry, I did not mention that the correct path to the logs is mentioned in the output: `D:\repositories\ideaIndexes\spring-framework\temp\ij-tmp-1688056322162\log`

**Comment by intellijboy** [comment]
### args.txt
```shell
E:\JetBrains\Toolbox\apps\IDEA-U\ch-1\231.9011.34\bin\idea64.exe
dump-shared-index
version
--output=D:\repositories\ideaIndexes\spring-framework\temp\ij-version-1688056321490\IU-231.9011.34\version.json
```
### env.txt
```shell
=D:=D:\repositories\ideaIndexes
=E:=E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\bin
=ExitCode=00000001
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\Administrator\AppData\Roaming
APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL=true
APP_BASE_NAME=ij-shared-indexes-tool-cli
APP_HOME=E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1
CHROME_CRASHPAD_PIPE_NAME=\\.\pipe\crashpad_12320_TOJFIJFGPHWIWFQI
CLASSPATH=E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\ij-shared-indexes-tool-cli-0.9.1.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\ij-shared-indexes-tool-0.9.1.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\cdn-layout-local-0.9.1.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\cdn-layout-s3-0.9.1.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\cdn-layout-common-0.9.1.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\ij-downloader-0.9.1.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\ij-runner-0.9.1.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\ij-unpack-common-0.9.1.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\ij-exec-common-0.9.1.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\ij-common-0.9.1.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\ij-downloader-common-0.9.1.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\ij-shared-indexes-simple-server-0.9.1.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\ktor-server-partial-content-jvm-2.2.4.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\ktor-server-auto-head-response-jvm-2.2.4.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\ktor-server-netty-jvm-2.2.4.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\ktor-server-host-common-jvm-2.2.4.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\ktor-server-conditional-headers-jvm-2.2.4.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\ktor-server-core-jvm-2.2.4.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\okhttp-4.10.0.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\okio-jvm-3.0.0.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\ktor-serialization-jvm-2.2.4.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\ktor-events-jvm-2.2.4.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\ktor-websockets-jvm-2.2.4.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\ktor-http-cio-jvm-2.2.4.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\ktor-http-jvm-2.2.4.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\ktor-network-jvm-2.2.4.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\ktor-utils-jvm-2.2.4.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\ktor-io-jvm-2.2.4.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\kotlin-stdlib-jdk8-1.7.22.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\jackson-databind-2.14.2.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\jackson-core-2.14.2.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\jackson-annotations-2.14.2.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\jackson-module-kotlin-2.14.2.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\kotlin-reflect-1.7.22.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\logback-classic-1.4.6.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\s3-2.20.17.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\aws-xml-protocol-2.20.17.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\aws-query-protocol-2.20.17.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\protocol-core-2.20.17.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\aws-core-2.20.17.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\auth-2.20.17.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\regions-2.20.17.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\sdk-core-2.20.17.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\apache-client-2.20.17.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\arns-2.20.17.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\profiles-2.20.17.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\netty-nio-client-2.20.17.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\http-client-spi-2.20.17.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\metrics-spi-2.20.17.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\json-utils-2.20.17.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\utils-2.20.17.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\slf4j-api-2.0.6.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\jcommander-1.82.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\kotlin-stdlib-jdk7-1.7.22.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\kotlin-stdlib-1.7.22.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\logback-core-1.4.6.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\kotlinx-coroutines-jdk8-1.6.4.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\kotlinx-coroutines-core-jvm-1.6.4.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\kotlin-stdlib-common-1.7.22.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\annotations-13.0.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\xz-1.9.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\endpoints-spi-2.20.17.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\annotations-2.20.17.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\httpclient-4.5.13.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\httpcore-4.4.13.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\commons-codec-1.15.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\config-1.4.2.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\jansi-2.4.0.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\netty-codec-http2-4.1.86.Final.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\alpn-api-1.1.3.v20160715.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\netty-transport-native-kqueue-4.1.86.Final.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\netty-transport-native-epoll-4.1.86.Final.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\reactive-streams-1.0.3.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\eventstream-1.0.1.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\third-party-jackson-core-2.20.17.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\netty-codec-http-4.1.86.Final.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\netty-handler-4.1.86.Final.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\netty-codec-4.1.86.Final.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\netty-transport-classes-epoll-4.1.86.Final.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\netty-transport-classes-kqueue-4.1.86.Final.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\netty-transport-native-unix-common-4.1.86.Final.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\netty-transport-4.1.86.Final.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\netty-buffer-4.1.86.Final.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\netty-resolver-4.1.86.Final.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\netty-common-4.1.86.Final.jar;E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\lib\commons-logging-1.2.jar
COLORTERM=truecolor
COMPUTERNAME=INTELLIJBOY
ComSpec=C:\WINDOWS\system32\cmd.exe
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
DIRNAME=E:\intellijboy-devkits\ij-shared-indexes-tool-cli-0.9.1\bin\
DriverData=C:\Windows\System32\Drivers\DriverData
GIT_ASKPASS=c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass.sh
GRADLE_HOME=D:\repositories\gradle\wrapper\dists\gradle-7.6.1-bin\2clxi94ab3brv6467628wnxmd\gradle-7.6.1
GRADLE_USER_HOME=D:\repositories\gradle
HOMEDRIVE=C:
HOMEPATH=\Users\Administrator
IDEA_VM_OPTIONS=D:\repositories\ideaIndexes\spring-framework\temp\ij-tmp-1688056322162\231.9011.34.vmoptions
JAVA_EXE=E:\intellijboy-sdk\jdk\openjdk-17.0.1/bin/java.exe
JAVA_HOME=E:\intellijboy-sdk\jdk\openjdk-17.0.1
KOTLIN_HOME=E:\intellijboy-sdk\kotlin-compiler-1.7.21\kotlinc
LANG=zh_CN.UTF-8
LOCALAPPDATA=C:\Users\Administrator\AppData\Local
LOGONSERVER=\\INTELLIJBOY
MAVEN_HOME=E:\intellijboy-devkits\apache-maven-3.6.0
MONGO_HOME=E:\intellijboy-middleware\mongodb-win32-x86_64-windows-4.4.4
MYSQL_HOME=E:\intellijboy-devkits\mysql-8.0.28-winx64
NUMBER_OF_PROCESSORS=12
NVM_HOME=E:\intellijboy-devkits\nvm
NVM_SYMLINK=E:\intellijboy-devkits\nodejs
OS=Windows_NT
OneDrive=C:\Users\Administrator\OneDrive
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PMD_HOME=E:\intellijboy-devkits\pmd-bin-7.0.0-rc3
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=9e0a
PROMPT=$P$G
PSModulePath=%ProgramFiles%\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
Path=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;E:\intellijboy-sdk\jdk\openjdk-17.0.1\bin;E:\intellijboy-software\Xshell 7\Xmanager 7\;E:\intellijboy-software\Xshell 7\Xftp 7\;E:\intellijboy-software\Xshell 7\Xlpd 7\;E:\intellijboy-devkits\Git\cmd;D:\repositories\gradle\wrapper\dists\gradle-7.6.1-bin\2clxi94ab3brv6467628wnxmd\gradle-7.6.1\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;E:\intellijboy-devkits\Typora;E:\Program Files (x86)\NetSarang\Xshell 7\;E:\intellijboy-devkits\apache-maven-3.6.0\bin;E:\intellijboy-devkits\nvm;E:\intellijboy-devkits\nodejs;D:\repositories\nodejs\node_gobal;E:\intellijboy-devkits\mysql-8.0.28-winx64\bin;E:\intellijboy-middleware\mongodb-win32-x86_64-windows-4.4.4\bin;E:\intellijboy-sdk\kotlin-compiler-1.7.21\kotlinc\bin;E:\intellijboy-software\zip-3.0-bin\bin;C:\Program Files (x86)\Bito\;E:\intellijboy-devkits\pmd-bin-7.0.0-rc3\bin;E:\intellijboy-devkits\dependency-check-8.3.1-release\bin;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Users\Administrator\AppData\Local\JetBrains\Toolbox\scripts;C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\bin
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=D:\repositories\ideaIndexes\spring-framework\temp\ij-tmp-1688056322162\system
TERM_PROGRAM=vscode
TERM_PROGRAM_VERSION=1.70.2
TMP=D:\repositories\ideaIndexes\spring-framework\temp\ij-tmp-1688056322162\system
TMPDIR=D:\repositories\ideaIndexes\spring-framework\temp\ij-tmp-1688056322162\system
USERDOMAIN=INTELLIJBOY
USERDOMAIN_ROAMINGPROFILE=INTELLIJBOY
USERNAME=Administrator
USERPROFILE=C:\Users\Administrator
VSCODE_GIT_ASKPASS_EXTRA_ARGS=--ms-enable-electron-run-as-node
VSCODE_GIT_ASKPASS_MAIN=c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass-main.js
VSCODE_GIT_ASKPASS_NODE=C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\Code.exe
VSCODE_GIT_IPC_HANDLE=\\.\pipe\vscode-git-97b3ffa46d-sock
WSLENV=WT_SESSION::WT_PROFILE_ID
WT_PROFILE_ID={0caa0dad-35be-5f56-a8ff-afceeeaa6101}
ZES_ENABLE_SYSMAN=1
windir=C:\WINDOWS
```
### vmoptions.txt
```shell
-Xmx1994m
#  -Dide.no.platform.update=true
-Dtoolbox.notification.token=vfM2Q5Wu_UL68PVtM7UinCPs7QP5-o3K0nomsT6Ee0U=
-Dtoolbox.notification.portFile=E:\JetBrains\Toolbox\apps\IDEA-U\ch-1\231.9011.34.vmoptions.port
#  -Didea.plugins.path=D:\repositories\ideaSetting\plugins
#  -Didea.system.path=D:\repositories\ideaSetting\system
#  -Didea.config.path=D:\repositories\ideaSetting\config
#  -Didea.log.path=D:\repositories\ideaSetting\log
-Dfile.encoding=UTF-8




#  IntelliJ Runner






#  IntelliJ Runner Defaults



-Djava.awt.headless=true
-Dide.no.platform.update=true
-Didea.config.path=D:\repositories\ideaIndexes\spring-framework\temp\ij-tmp-1688056322162\config
-Didea.system.path=D:\repositories\ideaIndexes\spring-framework\temp\ij-tmp-1688056322162\system
-Didea.plugins.path=D:\repositories\ideaIndexes\spring-framework\temp\ij-tmp-1688056322162\config
-Didea.log.path=D:\repositories\ideaIndexes\spring-framework\temp\ij-tmp-1688056322162\log
-Dide.browser.jcef.enabled=false
-Djava.io.tmpdir=D:\repositories\ideaIndexes\spring-framework\temp\ij-tmp-1688056322162
-Dvcs.log.index.git=false
-XX:+HeapDumpOnOutOfMemoryError
-XX:HeapDumpPath=D:\repositories\ideaIndexes\spring-framework\temp\ij-tmp-1688056322162\log
-XX:+CrashOnOutOfMemoryError
-XX:ErrorFile=D:\repositories\ideaIndexes\spring-framework\temp\ij-tmp-1688056322162\log
```

**Comment by sproshev** [comment]
@intellijboy Hi! My current guess is that the passed IDEA is already opened and by some reason the tool can not re-use it, am I right? I keep investigating, I will try to understand if it can be fixed

**Comment by intellijboy** [comment]
@sproshev thank you for you tip.it all works now
```shell
Put the following lines into D:\SOURCE-CODE-2023\project-template\SpringBoot2.7.0\intellij.yaml:
sharedIndex:
    project:
        - url: http://127.0.0.1:25561/project/springboot2.7.0
    consents:
        - kind: project
          decision: allowed

2023-07-21 00:37:03.629 [main] INFO  ktor.application - Autoreload is disabled because the development mode is off.
2023-07-21 00:37:03.723 [main] INFO  ktor.application - Application started in 0.173 seconds.
2023-07-21 00:37:04.356 [DefaultDispatcher-worker-2] INFO  ktor.application - Responding at http://127.0.0.1:25561

```

**Comment by sproshev** [comment]
@intellijboy what boost have you achieved?

**Comment by intellijboy** [comment]
@sproshev it just a open the box experience,and my example code is springboot java gradle quick start code.

**Comment by intellijboy** [comment]
I have some questions

- What's the difference between `indexes` and `boost`？
- project shared indexes include what types? include jdk indexes,maven indexes or just project indexes ?
- project shared indexes generate seemed to take a long time,can it execute without ij? (just use a gradle plugin or maven plugin or idea built-in plugin)

**Comment by 0815pascal** [comment]
> @intellijboy Hi! My current guess is that the passed IDEA is already opened and by some reason the tool can not re-use it, am I right? I keep investigating, I will try to understand if it can be fixed

Came here for the same problem, but had IntelliJ already open. Closed it and it works -- thank you :)

**Comment by sproshev** [comment]
@intellijboy Hi! Sorry for the long delay, I was on vacation.

- `indexes` is a part of `boost`, `indexes` command builds shared indexes and updates layout in `DATA_DIRECTORY/server` so that `DD/server/data` and `DD/server/project` can be synced with the same directories on a file server or S3. `boost` command runs IJ without shared indexes, measures indexing time, then runs `indexes-server` internally and then runs IJ with shared indexes. After that, indexing time is compared and printed to the output. So `boost` is recommended for a quick evaluation, `indexes` is recommended for the usual daily/weekly shared indexes generation.
- project shared indexes include indexes for a project sources and its dependencies, jdk, maven, everything that is used in a project.
- IJ is required at the moment. To build project shared indexes properly, there should be knowledge about project structure and its dependencies, IJ does this part pretty well. I'm not sure I got this question, what do you mean without IJ but with idea built-in plugin?
