### ISSUE TITLE
Can not find `indexing-diagnostic` directory in `ij-shared-indexes-tool-data`

### ISSUE THREAD

**Issue by OussamaHaff** [JetBrains/intellij-shared-indexes-tool-example#3]
# Context
I'm trying to evaluate indexing time with shared indexes in a large Android project as described in the official doc: https://www.jetbrains.com/help/idea/shared-indexes.html#evaluate_saved_time_boost

### Expectation
Script should print a summary comparing IDE perfomance with and without shared indexing.

### Observation

- Script terminated with an error `Can not find indexing-diagnostic directory`
```
2023-07-27 23:50:25.081 [main] INFO  c.i.extras.runner.IntelliJRunner - IU-232.8660.185 completed with code: 0
2023-07-27 23:50:25.083 [main] INFO  c.i.indexing.shared.builder.IntelliJ - Deleting /Users/UUUUUU/Projects/PPPPP/intellij.yaml
Exception in thread "main" java.lang.IllegalStateException: Can not find indexing-diagnostic directory in /Users/UUUUUU/Projects/PPPPP/ij-shared-indexes-tool-cli-0.9.8/ij-shared-indexes-tool-data/temp/ij-tmp-1690494115745/log
	at com.intellij.indexing.shared.builder.ShortcutsKt.findIndexingDiagnostic(Shortcuts.kt:294)
	at com.intellij.indexing.shared.builder.ShortcutsKt.findReportHtmlDir(Shortcuts.kt:261)
	at com.intellij.indexing.shared.builder.ShortcutsKt.warmupRun(Shortcuts.kt:257)
	at com.intellij.indexing.shared.builder.ShortcutsKt.measureSharedIndexesBoost(Shortcuts.kt:169)
	at com.intellij.indexing.shared.builder.ShortcutsKt.measureSharedIndexesBoost(Shortcuts.kt:130)
	at com.intellij.indexing.shared.builder.ShortcutsKt.measureSharedIndexesBoost$default(Shortcuts.kt:119)
	at com.intellij.indexing.shared.builder.MainKt.main(Main.kt:53)
``` 
- The folder mentioned in the error contains only 3 files and does not contain `indexing-diagnostic` directory.
<img width="735" alt="Screenshot 2023-07-28 at 00 17 15" src="https://github.com/JetBrains/intellij-shared-indexes-tool-example/assets/9051631/15a59e6f-8ca4-403d-9489-7e90e302ffc7">

### Attempts to resolve
- [x] Run command with `sudo` ❌ Got the same error.

# Used command
`./bin/ij-shared-indexes-tool-cli boost --ij "/Users/UUUUUU/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/232.8660.185/IntelliJ IDEA.app" --project "/Users/UUUUUU/Projects/PPPPP"`
- `UUUUUU` the local user who has full admin rights
- `PPPPP` the large Android project

# Environment 
- Shared indexes version `ij-shared-indexes-tool-cli-0.9.8` (check also the result of running `./bin/ij-shared-indexes-tool-cli version --ij "/Users/UUUUUU/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/232.8660.185/IntelliJ IDEA.app"` here: [shared-indexes-version-summary.txt](https://github.com/JetBrains/intellij-shared-indexes-tool-example/files/12188513/shared-indexes-version-summary.txt)
- JDK 11.0.18 
- Kotlin 1.8.22
- MacOS Ventura 13.5 / Apple Chip
- IntelliJ IDEA Ultimate 2023.2

# Appendix
Last logs before error with error:
```
2023-07-27 23:50:09.026 [exec-OutputReader] INFO  c.i.extras.common.process.ExecUtil - [IJ-Output]: ... keep running Awaiting for progress tasks.... so far 7 m 20 s 364 ms
2023-07-27 23:50:14.031 [exec-OutputReader] INFO  c.i.extras.common.process.ExecUtil - [IJ-Output]: ... keep running Awaiting for progress tasks.... so far 7 m 25 s 369 ms
2023-07-27 23:50:17.372 [exec-OutputReader] INFO  c.i.extras.common.process.ExecUtil - [IJ-Output]: Waiting for 'Later Invocations in EDT'...
2023-07-27 23:50:17.372 [exec-OutputReader] INFO  c.i.extras.common.process.ExecUtil - [IJ-Output]: Completed waiting for 'Later Invocations in EDT' in 0 ms
2023-07-27 23:50:17.696 [exec-ErrorReader] INFO  c.i.extras.common.process.ExecUtil - [IJ-Error]: 2023-07-27 23:50:17,696 [ 501739]   WARN - #o.j.i.maven - process artifacts: 0
2023-07-27 23:50:17.759 [exec-ErrorReader] INFO  c.i.extras.common.process.ExecUtil - [IJ-Error]: 2023-07-27 23:50:17,759 [ 501802]   WARN - #o.j.i.maven - process artifacts: 7
2023-07-27 23:50:18.378 [exec-OutputReader] INFO  c.i.extras.common.process.ExecUtil - [IJ-Output]: Waiting for 'Later Invocations in EDT'...
2023-07-27 23:50:18.382 [exec-OutputReader] INFO  c.i.extras.common.process.ExecUtil - [IJ-Output]: Completed waiting for 'Later Invocations in EDT' in 3 ms
2023-07-27 23:50:18.385 [exec-OutputReader] INFO  c.i.extras.common.process.ExecUtil - [IJ-Output]: Completed waiting for 'Awaiting for progress tasks' in 7 m 29 s 723 ms
2023-07-27 23:50:18.385 [exec-OutputReader] INFO  c.i.extras.common.process.ExecUtil - [IJ-Output]: Waiting for 'RefreshQueue'...
2023-07-27 23:50:18.385 [exec-OutputReader] INFO  c.i.extras.common.process.ExecUtil - [IJ-Output]: Completed waiting for 'RefreshQueue' in 0 ms
2023-07-27 23:50:19.834 [exec-ErrorReader] INFO  c.i.extras.common.process.ExecUtil - [IJ-Error]: 2023-07-27 23:50:19,834 [ 503877]   WARN - #c.i.u.x.Binding - no accessors for java.time.LocalTime
2023-07-27 23:50:24.004 [exec-OutputReader] INFO  c.i.extras.common.process.ExecUtil - [IJ-Output]: IDE Warm-up finished. 672709 files were indexed. Exiting the application...
2023-07-27 23:50:25.079 [main] INFO  c.i.extras.common.process.ExecUtil -   ... successfully finished external process for IJ with exit code 0
2023-07-27 23:50:25.081 [main] INFO  c.i.extras.runner.IntelliJRunner - IU-232.8660.185 completed with code: 0
2023-07-27 23:50:25.083 [main] INFO  c.i.indexing.shared.builder.IntelliJ - Deleting /Users/UUUUUU/Projects/PPPPP/intellij.yaml
Exception in thread "main" java.lang.IllegalStateException: Can not find indexing-diagnostic directory in /Users/UUUUUU/Projects/PPPPP/ij-shared-indexes-tool-cli-0.9.8/ij-shared-indexes-tool-data/temp/ij-tmp-1690494115745/log
	at com.intellij.indexing.shared.builder.ShortcutsKt.findIndexingDiagnostic(Shortcuts.kt:294)
	at com.intellij.indexing.shared.builder.ShortcutsKt.findReportHtmlDir(Shortcuts.kt:261)
	at com.intellij.indexing.shared.builder.ShortcutsKt.warmupRun(Shortcuts.kt:257)
	at com.intellij.indexing.shared.builder.ShortcutsKt.measureSharedIndexesBoost(Shortcuts.kt:169)
	at com.intellij.indexing.shared.builder.ShortcutsKt.measureSharedIndexesBoost(Shortcuts.kt:130)
	at com.intellij.indexing.shared.builder.ShortcutsKt.measureSharedIndexesBoost$default(Shortcuts.kt:119)
	at com.intellij.indexing.shared.builder.MainKt.main(Main.kt:53)
```

**Comment by sproshev** [comment]
Hi! Sorry for the delay, I was on vacation, could you please attach vmoptions.txt? It should contain paths to config and system directories for further investigation

**Comment by pschwarzer-tt** [comment]
Hi, i also see this issue, after calling:

```
ij-shared-indexes-tool-cli.bat boost --ij "C:\Users\nightlybuild\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\232.9559.62" --project "E:\w\19f8fce6a6742369" --data-directory "E:\IntelliJ\temp"
```

```
13:21:15   Exception in thread "main" java.lang.IllegalStateException: Can not find indexing-diagnostic directory in E:\IntelliJ\temp\temp\ij-tmp-1693394278413\log
13:21:15     at com.intellij.indexing.shared.builder.ShortcutsKt.findIndexingDiagnostic(Shortcuts.kt:294)
13:21:15     at com.intellij.indexing.shared.builder.ShortcutsKt.findReportHtmlDir(Shortcuts.kt:261)
13:21:15     at com.intellij.indexing.shared.builder.ShortcutsKt.warmupRun(Shortcuts.kt:257)
13:21:15     at com.intellij.indexing.shared.builder.ShortcutsKt.measureSharedIndexesBoost(Shortcuts.kt:169)
13:21:15     at com.intellij.indexing.shared.builder.ShortcutsKt.measureSharedIndexesBoost(Shortcuts.kt:130)
13:21:15     at com.intellij.indexing.shared.builder.ShortcutsKt.measureSharedIndexesBoost$default(Shortcuts.kt:119)
13:21:15     at com.intellij.indexing.shared.builder.MainKt.main(Main.kt:53)
13:21:15   Process exited with code 1
```

Issue happend after second call of `ij-shared-indexes-tool-cli.bat boost` (first run failed because intellij.yaml was readonly in --project) and now continously occur. Deleting the --data-directory or the whole --project directory could not fix the problem.

Additional stuff:
[data_directory_content.zip](https://github.com/JetBrains/intellij-shared-indexes-tool-example/files/12475626/data_directory_content.zip)

**Comment by Jonghakseo** [comment]
Hi. I'm having the same issue.
[ij-tmp-1725935129945.zip](https://github.com/user-attachments/files/16938570/ij-tmp-1725935129945.zip)

```bash
2024-09-10 11:25:39.982 [exec-OutputReader] INFO  c.i.extras.common.process.ExecUtil - [IJ-Output]: IDE Warm-up finished.
2024-09-10 11:25:39.982 [exec-OutputReader] INFO  c.i.extras.common.process.ExecUtil - [IJ-Output]:  - Elapsed time: 9 s 581 ms
2024-09-10 11:25:39.982 [exec-OutputReader] INFO  c.i.extras.common.process.ExecUtil - [IJ-Output]:  - Number of indexed files: 0.
2024-09-10 11:25:39.982 [exec-OutputReader] INFO  c.i.extras.common.process.ExecUtil - [IJ-Output]: Exiting the application...
2024-09-10 11:25:40.537 [main] INFO  c.i.extras.common.process.ExecUtil -   ... successfully finished external process for IJ with exit code 0
2024-09-10 11:25:40.538 [main] INFO  c.i.extras.runner.IntelliJRunner - WS-241.18034.50 completed with code: 0
2024-09-10 11:25:40.539 [main] INFO  c.i.indexing.shared.builder.IntelliJ - Deleting /Users/####/$$$$$/^^^^^/intellij.yaml
Exception in thread "main" java.lang.IllegalStateException: Can not find indexing-diagnostic directory in /Users/####/$$$$/ij-shared-indexes-tool-cli-0.9.9/ij-shared-indexes-tool-data/temp/ij-tmp-1725935129945/log
	at com.intellij.indexing.shared.builder.ShortcutsKt.findIndexingDiagnostic(Shortcuts.kt:267)
	at com.intellij.indexing.shared.builder.ShortcutsKt.findReportHtmlDir(Shortcuts.kt:234)
	at com.intellij.indexing.shared.builder.ShortcutsKt.warmupRun(Shortcuts.kt:230)
	at com.intellij.indexing.shared.builder.ShortcutsKt.measureSharedIndexesBoost(Shortcuts.kt:142)
	at com.intellij.indexing.shared.builder.ShortcutsKt.measureSharedIndexesBoost(Shortcuts.kt:103)
	at com.intellij.indexing.shared.builder.ShortcutsKt.measureSharedIndexesBoost$default(Shortcuts.kt:92)
	at com.intellij.indexing.shared.builder.MainKt.main(Main.kt:48)
```
